// HeaderMainNav Component Stub
// Generated by Frontend-Scaffold Agent
// FORBIDDEN: Business logic, API calls, inline styles

import React from 'react';
import { HeaderMainNavProps } from '../../types/components';
import styles from './HeaderMainNav.module.css';

export const HeaderMainNav: React.FC<HeaderMainNavProps> = ({
    minimal = false,
    adminMode = false,
    user = null,
    onLogin,
    onLogout,
}) => {
    return (
        <header className={`${styles.header} ${minimal ? styles.minimal : ''} ${adminMode ? styles.admin : ''}`}>
            <div className={styles.container}>
                {/* Logo slot */}
                <div className={styles.logo}>
                    <a href="/">3D Commerce</a>
                </div>

                {/* Nav slot */}
                {!minimal && (
                    <nav className={styles.nav}>
                        <a href="/store" className={styles.navLink}>Store</a>
                        <a href="/upload" className={styles.navLink}>Upload</a>
                        {adminMode && <a href="/admin" className={styles.navLink}>Dashboard</a>}
                    </nav>
                )}

                {/* Actions slot */}
                <div className={styles.actions}>
                    {!adminMode && (
                        <a href="/cart" className={styles.actionBtn}>
                            Cart
                        </a>
                    )}
                    {user ? (
                        <button onClick={onLogout} className={styles.actionBtn}>
                            Logout
                        </button>
                    ) : (
                        <button onClick={onLogin} className={styles.actionBtn}>
                            Login
                        </button>
                    )}
                </div>

                {/* Plugin slot */}
                <div className={styles.pluginSlot} data-slot="header-plugin" />
            </div>
        </header>
    );
};

export default HeaderMainNav;
