// Security Tests for Golden Path
// Generated by Test-Generation Agent

import { test, expect } from '@playwright/test';

test.describe('Security - IDOR Prevention', () => {
    test('Customer cannot view other customer orders', async ({ request }) => {
        // Login as customer A
        const loginA = await request.post('/api/auth/login', {
            data: { email: 'customerA@example.com', password: 'password' }
        });
        const tokenA = (await loginA.json()).token;

        // Create order as customer A
        const orderA = await request.post('/api/orders', {
            headers: { Authorization: `Bearer ${tokenA}` },
            data: { shippingAddress: {}, paymentMethod: 'mock' }
        });
        const orderIdA = (await orderA.json()).order.id;

        // Login as customer B
        const loginB = await request.post('/api/auth/login', {
            data: { email: 'customerB@example.com', password: 'password' }
        });
        const tokenB = (await loginB.json()).token;

        // Customer B tries to access Customer A's order
        const response = await request.get(`/api/orders/${orderIdA}`, {
            headers: { Authorization: `Bearer ${tokenB}` }
        });

        expect(response.status()).toBe(403);
    });

    test('Customer cannot access admin dashboard', async ({ request }) => {
        // Login as customer
        const login = await request.post('/api/auth/login', {
            data: { email: 'customer@example.com', password: 'password' }
        });
        const token = (await login.json()).token;

        const response = await request.get('/api/admin/dashboard', {
            headers: { Authorization: `Bearer ${token}` }
        });

        expect(response.status()).toBe(403);
    });

    test('Customer cannot manage API keys', async ({ request }) => {
        const login = await request.post('/api/auth/login', {
            data: { email: 'customer@example.com', password: 'password' }
        });
        const token = (await login.json()).token;

        const response = await request.post('/api/admin/api-keys', {
            headers: { Authorization: `Bearer ${token}` },
            data: { provider: 'mock', apiKey: 'stolen', enabled: true }
        });

        expect(response.status()).toBe(403);
    });
});

test.describe('Security - Role Escalation Prevention', () => {
    test('Customer cannot update order status', async ({ request }) => {
        const login = await request.post('/api/auth/login', {
            data: { email: 'customer@example.com', password: 'password' }
        });
        const token = (await login.json()).token;

        // Create own order
        const order = await request.post('/api/orders', {
            headers: { Authorization: `Bearer ${token}` },
            data: { shippingAddress: {}, paymentMethod: 'mock' }
        });
        const orderId = (await order.json()).order.id;

        // Try to update status (admin only)
        const response = await request.patch(`/api/orders/${orderId}`, {
            headers: { Authorization: `Bearer ${token}` },
            data: { status: 'shipped' }
        });

        expect(response.status()).toBe(403);
    });

    test('Customer cannot trigger AI layout change', async ({ request }) => {
        const login = await request.post('/api/auth/login', {
            data: { email: 'customer@example.com', password: 'password' }
        });
        const token = (await login.json()).token;

        const response = await request.post('/api/admin/layout', {
            headers: { Authorization: `Bearer ${token}` },
            data: { prompt: 'Change layout', screen: 'checkout' }
        });

        expect(response.status()).toBe(403);
    });
});

test.describe('Security - Unauthenticated Access', () => {
    test('Cannot access cart without authentication', async ({ request }) => {
        const response = await request.get('/api/cart');
        expect(response.status()).toBe(401);
    });

    test('Cannot create order without authentication', async ({ request }) => {
        const response = await request.post('/api/orders', {
            data: { shippingAddress: {}, paymentMethod: 'mock' }
        });
        expect(response.status()).toBe(401);
    });
});
