// PricingBox Component Stub
// Generated by Frontend-Scaffold Agent

import React from 'react';
import { PricingBoxProps } from '../../types/components';
import styles from './PricingBox.module.css';

export const PricingBox: React.FC<PricingBoxProps> = ({
    pricing,
    quantity,
    onQuantityChange,
    onAddToCart,
}) => {
    return (
        <div className={styles.pricingBox}>
            <h3 className={styles.title}>Price Estimate</h3>

            <div className={styles.breakdown}>
                <div className={styles.row}>
                    <span>Base Price</span>
                    <span>${pricing.basePrice.toFixed(2)}</span>
                </div>
                <div className={styles.row}>
                    <span>Material</span>
                    <span>+${pricing.materialCost.toFixed(2)}</span>
                </div>
                <div className={styles.row}>
                    <span>Size Factor</span>
                    <span>×{pricing.sizeFactor.toFixed(2)}</span>
                </div>
                {pricing.discount > 0 && (
                    <div className={`${styles.row} ${styles.discount}`}>
                        <span>Discount</span>
                        <span>-${pricing.discount.toFixed(2)}</span>
                    </div>
                )}
            </div>

            <div className={styles.quantityRow}>
                <label>Quantity</label>
                <div className={styles.quantityControl}>
                    <button
                        onClick={() => onQuantityChange?.(Math.max(1, quantity - 1))}
                        className={styles.qtyBtn}
                    >
                        -
                    </button>
                    <span className={styles.qtyValue}>{quantity}</span>
                    <button
                        onClick={() => onQuantityChange?.(quantity + 1)}
                        className={styles.qtyBtn}
                    >
                        +
                    </button>
                </div>
            </div>

            <div className={styles.total}>
                <span>Total</span>
                <span className={styles.totalValue}>${(pricing.total * quantity).toFixed(2)}</span>
            </div>

            <button onClick={onAddToCart} className={styles.addToCart}>
                Add to Cart
            </button>

            <div className={styles.pluginSlot} data-slot="pricing-plugin" />
        </div>
    );
};

export default PricingBox;
