// Golden Path E2E Tests
// Generated by Test-Generation Agent
// Covers: User places order, Admin sees order

import { test, expect } from '@playwright/test';

test.describe('Golden Path - Customer Flow', () => {
    test('User can upload 3D file and configure print', async ({ page }) => {
        await page.goto('/upload');

        // Upload file
        const fileInput = page.locator('input[type="file"]');
        await fileInput.setInputFiles('./test-fixtures/cube.stl');

        // Wait for model viewer to appear
        await expect(page.locator('[data-testid="model-viewer"]')).toBeVisible();

        // Configure material
        await page.click('[data-testid="material-pla"]');
        await page.click('[data-testid="color-blue"]');

        // Check pricing updates
        await expect(page.locator('[data-testid="total-price"]')).toContainText('$');
    });

    test('User can add to cart and checkout', async ({ page }) => {
        // Pre-condition: item configured
        await page.goto('/upload');
        await page.locator('input[type="file"]').setInputFiles('./test-fixtures/cube.stl');
        await page.waitForSelector('[data-testid="model-viewer"]');

        // Add to cart
        await page.click('[data-testid="add-to-cart"]');
        await expect(page.locator('[data-testid="cart-count"]')).toContainText('1');

        // Go to cart
        await page.goto('/cart');
        await expect(page.locator('[data-testid="cart-item"]')).toHaveCount(1);

        // Proceed to checkout
        await page.click('[data-testid="checkout-btn"]');

        // Auth redirect (mock login)
        await page.waitForURL('/login*');
        await page.fill('[data-testid="email"]', 'test@example.com');
        await page.fill('[data-testid="password"]', 'testpassword');
        await page.click('[data-testid="login-btn"]');

        // Should redirect to checkout
        await page.waitForURL('/checkout');
    });

    test('User can complete checkout with mock payment', async ({ page }) => {
        // Pre-condition: logged in with cart
        await page.goto('/checkout');

        // Fill shipping form
        await page.fill('[data-testid="shipping-name"]', 'Test User');
        await page.fill('[data-testid="shipping-street"]', '123 Test St');
        await page.fill('[data-testid="shipping-city"]', 'Test City');
        await page.fill('[data-testid="shipping-postal"]', '12345');
        await page.selectOption('[data-testid="shipping-country"]', 'US');

        // Mock payment
        await page.click('[data-testid="mock-pay-btn"]');

        // Should redirect to confirmation
        await page.waitForURL('/order/**/confirmation');
        await expect(page.locator('[data-testid="success-message"]')).toBeVisible();
        await expect(page.locator('[data-testid="order-id"]')).toBeVisible();
    });
});

test.describe('Golden Path - Admin Flow', () => {
    test.beforeEach(async ({ page }) => {
        // Login as admin
        await page.goto('/login');
        await page.fill('[data-testid="email"]', 'admin@example.com');
        await page.fill('[data-testid="password"]', 'adminpassword');
        await page.click('[data-testid="login-btn"]');
    });

    test('Admin can view dashboard with KPIs', async ({ page }) => {
        await page.goto('/admin');

        await expect(page.locator('[data-testid="kpi-grid"]')).toBeVisible();
        await expect(page.locator('[data-testid="printer-status"]')).toBeVisible();
        await expect(page.locator('[data-testid="order-queue"]')).toBeVisible();
    });

    test('Admin can see customer order in queue', async ({ page }) => {
        await page.goto('/admin');

        // Order from customer flow should appear
        await expect(page.locator('[data-testid="order-queue"]')).toContainText('pending');
    });

    test('Admin can change layout via AI prompt', async ({ page }) => {
        await page.goto('/admin');

        // Find prompt box
        const promptBox = page.locator('[data-testid="ai-prompt-box"]');
        await promptBox.fill('Make the checkout layout more compact.');
        await page.click('[data-testid="ai-submit"]');

        // Should show preview
        await expect(page.locator('[data-testid="layout-preview"]')).toBeVisible();

        // Apply change
        await page.click('[data-testid="apply-layout"]');

        // Verify change persists
        await page.reload();
        // Layout config should be updated
        await expect(page.locator('[data-testid="layout-applied"]')).toBeVisible();
    });
});
