// FileUpload Component Stub
// Generated by Frontend-Scaffold Agent

import React, { useCallback } from 'react';
import { FileUploadProps } from '../../types/components';
import styles from './FileUpload.module.css';

export const FileUpload: React.FC<FileUploadProps> = ({
    accept = ['.stl', '.obj', '.3mf'],
    onFileSelect,
    onUploadComplete,
}) => {
    const handleDrop = useCallback((e: React.DragEvent) => {
        e.preventDefault();
        const file = e.dataTransfer.files[0];
        if (file && onFileSelect) {
            onFileSelect(file);
        }
    }, [onFileSelect]);

    const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const file = e.target.files?.[0];
        if (file && onFileSelect) {
            onFileSelect(file);
        }
    }, [onFileSelect]);

    return (
        <div className={styles.uploadContainer}>
            <div
                className={styles.dropzone}
                onDrop={handleDrop}
                onDragOver={(e) => e.preventDefault()}
            >
                <div className={styles.icon}>📦</div>
                <h3 className={styles.title}>Drop your 3D file here</h3>
                <p className={styles.subtitle}>or click to browse</p>
                <p className={styles.formats}>Supported: {accept.join(', ')}</p>
                <input
                    type="file"
                    accept={accept.join(',')}
                    onChange={handleChange}
                    className={styles.fileInput}
                />
            </div>
            <div className={styles.pluginSlot} data-slot="upload-plugin" />
        </div>
    );
};

export default FileUpload;
