// API Types - Auto-generated from golden_path_spec.md
// DO NOT EDIT - Generated by Frontend-Scaffold Agent

export interface Product {
    id: string;
    name: string;
    description: string;
    basePrice: number;
    images: string[];
    featured: boolean;
}

export interface Material {
    id: string;
    name: string;
    priceMultiplier: number;
    colors: string[];
    properties: Record<string, string>;
}

export interface PricingEstimate {
    basePrice: number;
    materialCost: number;
    sizeFactor: number;
    quantity: number;
    discount: number;
    total: number;
}

export interface CartItem {
    id: string;
    modelId: string;
    modelName: string;
    materialId: string;
    color: string;
    config: PrintConfig;
    quantity: number;
    price: number;
}

export interface Cart {
    items: CartItem[];
    subtotal: number;
    shipping: number;
    total: number;
}

export interface PrintConfig {
    scale: number;
    infill: number;
    supports: boolean;
    quality: 'draft' | 'standard' | 'high';
}

export interface Order {
    id: string;
    userId: string;
    status: 'pending' | 'processing' | 'printing' | 'shipped' | 'delivered' | 'cancelled';
    items: CartItem[];
    shippingAddress: Address;
    totalPrice: number;
    createdAt: string;
    updatedAt: string;
}

export interface Address {
    name: string;
    street: string;
    city: string;
    postalCode: string;
    country: string;
}

export interface AdminKPI {
    label: string;
    value: number;
    trend: number;
    trendDirection: 'up' | 'down' | 'neutral';
}

export interface Printer {
    id: string;
    name: string;
    status: 'idle' | 'printing' | 'maintenance' | 'error';
    progress: number;
    currentJob?: string;
}

export interface ApiKeyConfig {
    id: string;
    provider: string;
    enabled: boolean;
    createdAt: string;
}

export interface User {
    uid: string;
    email: string;
    displayName: string;
    role: 'customer' | 'admin' | 'super_admin';
}
