// Component Props Types - Auto-generated from screen compositions
// DO NOT EDIT - Generated by Frontend-Scaffold Agent

import { Product, Material, Cart, Order, AdminKPI, Printer, PrintConfig, PricingEstimate } from './api';

// Navigation
export interface HeaderMainNavProps {
    minimal?: boolean;
    adminMode?: boolean;
    user?: { displayName: string; role: string } | null;
    onLogin?: () => void;
    onLogout?: () => void;
}

// Commerce
export interface ProductGridProps {
    products: Product[];
    featuredOnly?: boolean;
    limit?: number;
    onProductClick?: (product: Product) => void;
}

export interface CartSummaryProps {
    cart: Cart;
    onQuantityChange?: (itemId: string, quantity: number) => void;
    onRemoveItem?: (itemId: string) => void;
    onCheckout?: () => void;
}

// 3D Printing
export interface FileUploadProps {
    accept?: string[];
    onFileSelect?: (file: File) => void;
    onUploadComplete?: (modelId: string) => void;
}

export interface ModelViewerProps {
    modelUrl?: string;
    onRotate?: (rotation: { x: number; y: number; z: number }) => void;
}

export interface ConfigPanelProps {
    config: PrintConfig;
    onChange?: (config: PrintConfig) => void;
}

export interface MaterialSelectorProps {
    materials: Material[];
    selectedMaterial?: string;
    selectedColor?: string;
    onMaterialChange?: (materialId: string) => void;
    onColorChange?: (color: string) => void;
}

export interface PricingBoxProps {
    pricing: PricingEstimate;
    quantity: number;
    onQuantityChange?: (quantity: number) => void;
    onAddToCart?: () => void;
}

// User
export interface OrderCardProps {
    order: Order;
    onViewDetails?: () => void;
    onTrack?: () => void;
}

// Admin
export interface KpiGridProps {
    kpis: AdminKPI[];
}

export interface PrinterStatusProps {
    printers: Printer[];
    onRefresh?: () => void;
}

export interface OrderQueueProps {
    orders: Order[];
    onStatusChange?: (orderId: string, status: Order['status']) => void;
    onViewDetails?: (orderId: string) => void;
}

// AI
export interface PromptBoxProps {
    placeholder?: string;
    quickPrompts?: string[];
    aiMode?: 'layout_change' | 'content' | 'general';
    onSubmit?: (prompt: string) => void;
}

// Forms
export interface ShippingFormProps {
    onSubmit?: (address: { name: string; street: string; city: string; postalCode: string; country: string }) => void;
}

export interface ApiKeyFormProps {
    onSave?: (config: { provider: string; apiKey: string; enabled: boolean }) => void;
}
