// Design Token Types - Auto-generated from design-tokens.json
// DO NOT EDIT - Generated by Frontend-Scaffold Agent

export type ColorToken = 
  | '--color-primary'
  | '--color-primary-hover'
  | '--color-secondary'
  | '--color-accent'
  | '--color-success'
  | '--color-warning'
  | '--color-error'
  | '--color-background'
  | '--color-surface'
  | '--color-surface-hover'
  | '--color-border'
  | '--color-text-primary'
  | '--color-text-secondary'
  | '--color-text-muted';

export type SpacingToken = 
  | '--space-xs'
  | '--space-sm'
  | '--space-md'
  | '--space-lg'
  | '--space-xl'
  | '--space-2xl'
  | '--space-3xl';

export type FontSizeToken =
  | '--font-size-heading-xl'
  | '--font-size-heading-lg'
  | '--font-size-heading-md'
  | '--font-size-heading-sm'
  | '--font-size-body-lg'
  | '--font-size-body-regular'
  | '--font-size-body-small'
  | '--font-size-caption';

export type ElevationToken =
  | '--elevation-sm'
  | '--elevation-md'
  | '--elevation-lg'
  | '--elevation-xl'
  | '--elevation-glow';

export type RadiusToken =
  | '--radius-sm'
  | '--radius-md'
  | '--radius-lg'
  | '--radius-xl'
  | '--radius-2xl'
  | '--radius-full';

export type MotionToken =
  | '--motion-fast'
  | '--motion-normal'
  | '--motion-slow';
