// API Client - Generated by Backend-Contract Agent
// All endpoints from golden_path_spec.md

const API_BASE = '/api';

export const api = {
    // Public endpoints
    products: {
        list: (params?: { featured?: boolean; limit?: number }) =>
            fetch(`${API_BASE}/products?${new URLSearchParams(params as any)}`).then(r => r.json()),
    },

    materials: {
        list: () => fetch(`${API_BASE}/materials`).then(r => r.json()),
    },

    pricing: {
        estimate: (data: { modelVolume: number; materialId: string; config: any }) =>
            fetch(`${API_BASE}/pricing/estimate`, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(data),
            }).then(r => r.json()),
    },

    upload: {
        file: (file: File) => {
            const formData = new FormData();
            formData.append('file', file);
            return fetch(`${API_BASE}/upload`, {
                method: 'POST',
                body: formData,
            }).then(r => r.json());
        },
    },

    // Authenticated endpoints
    cart: {
        get: (token: string) =>
            fetch(`${API_BASE}/cart`, {
                headers: { Authorization: `Bearer ${token}` },
            }).then(r => r.json()),

        add: (token: string, item: any) =>
            fetch(`${API_BASE}/cart`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token}`,
                },
                body: JSON.stringify({ item }),
            }).then(r => r.json()),
    },

    orders: {
        create: (token: string, data: { shippingAddress: any; paymentMethod: string }) =>
            fetch(`${API_BASE}/orders`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    Authorization: `Bearer ${token}`,
                },
                body: JSON.stringify(data),
            }).then(r => r.json()),

        get: (token: string, orderId: string) =>
            fetch(`${API_BASE}/orders/${orderId}`, {
                headers: { Authorization: `Bearer ${token}` },
            }).then(r => r.json()),
    },

    // Admin endpoints
    admin: {
        dashboard: (token: string) =>
            fetch(`${API_BASE}/admin/dashboard`, {
                headers: { Authorization: `Bearer ${token}` },
            }).then(r => r.json()),

        orders: (token: string, params?: { status?: string; limit?: number }) =>
            fetch(`${API_BASE}/admin/orders?${new URLSearchParams(params as any)}`, {
                headers: { Authorization: `Bearer ${token}` },
            }).then(r => r.json()),

        apiKeys: {
            list: (token: string) =>
                fetch(`${API_BASE}/admin/api-keys`, {
                    headers: { Authorization: `Bearer ${token}` },
                }).then(r => r.json()),

            create: (token: string, data: { provider: string; apiKey: string; enabled: boolean }) =>
                fetch(`${API_BASE}/admin/api-keys`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Authorization: `Bearer ${token}`,
                    },
                    body: JSON.stringify(data),
                }).then(r => r.json()),
        },

        layout: {
            update: (token: string, data: { prompt: string; screen: string }) =>
                fetch(`${API_BASE}/admin/layout`, {
                    method: 'POST',
                    headers: {
                        'Content-Type': 'application/json',
                        Authorization: `Bearer ${token}`,
                    },
                    body: JSON.stringify(data),
                }).then(r => r.json()),
        },
    },
};
