// CartSummary Component Stub
// Generated by Frontend-Scaffold Agent

import React from 'react';
import { CartSummaryProps } from '../../types/components';
import styles from './CartSummary.module.css';

export const CartSummary: React.FC<CartSummaryProps> = ({
    cart,
    onQuantityChange,
    onRemoveItem,
    onCheckout,
}) => {
    return (
        <div className={styles.cartSummary}>
            <h2 className={styles.title}>Your Cart</h2>

            {cart.items.length === 0 ? (
                <div className={styles.empty}>
                    <p>Your cart is empty</p>
                </div>
            ) : (
                <>
                    <div className={styles.items}>
                        {cart.items.map((item) => (
                            <div key={item.id} className={styles.item}>
                                <div className={styles.itemInfo}>
                                    <h4 className={styles.itemName}>{item.modelName}</h4>
                                    <p className={styles.itemMeta}>
                                        Material: {item.materialId} • Color: {item.color}
                                    </p>
                                </div>
                                <div className={styles.itemActions}>
                                    <div className={styles.quantity}>
                                        <button
                                            onClick={() => onQuantityChange?.(item.id, item.quantity - 1)}
                                            disabled={item.quantity <= 1}
                                        >
                                            -
                                        </button>
                                        <span>{item.quantity}</span>
                                        <button onClick={() => onQuantityChange?.(item.id, item.quantity + 1)}>
                                            +
                                        </button>
                                    </div>
                                    <span className={styles.itemPrice}>${(item.price * item.quantity).toFixed(2)}</span>
                                    <button
                                        onClick={() => onRemoveItem?.(item.id)}
                                        className={styles.removeBtn}
                                    >
                                        ×
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>

                    <div className={styles.totals}>
                        <div className={styles.row}>
                            <span>Subtotal</span>
                            <span>${cart.subtotal.toFixed(2)}</span>
                        </div>
                        <div className={styles.row}>
                            <span>Shipping</span>
                            <span>${cart.shipping.toFixed(2)}</span>
                        </div>
                        <div className={`${styles.row} ${styles.totalRow}`}>
                            <span>Total</span>
                            <span>${cart.total.toFixed(2)}</span>
                        </div>
                    </div>

                    <button onClick={onCheckout} className={styles.checkoutBtn}>
                        Proceed to Checkout
                    </button>
                </>
            )}

            <div className={styles.pluginSlot} data-slot="cart-plugin" />
        </div>
    );
};

export default CartSummary;
