// Unit Tests for Pricing Logic
// Generated by Test-Generation Agent

import { describe, it, expect } from 'vitest';

// Mock pricing calculation (server-side only)
function calculatePricing(params: {
    modelVolume: number;
    materialPriceMultiplier: number;
    quality: 'draft' | 'standard' | 'high';
    quantity: number;
}): {
    basePrice: number;
    materialCost: number;
    sizeFactor: number;
    qualityFactor: number;
    total: number;
} {
    const BASE_PRICE_PER_CM3 = 0.15;
    const QUALITY_MULTIPLIERS = { draft: 0.8, standard: 1.0, high: 1.5 };

    const basePrice = params.modelVolume * BASE_PRICE_PER_CM3;
    const materialCost = basePrice * (params.materialPriceMultiplier - 1);
    const sizeFactor = params.modelVolume > 100 ? 0.9 : 1.0; // Volume discount
    const qualityFactor = QUALITY_MULTIPLIERS[params.quality];

    const unitPrice = (basePrice + materialCost) * sizeFactor * qualityFactor;
    const total = unitPrice * params.quantity;

    return {
        basePrice: Math.round(basePrice * 100) / 100,
        materialCost: Math.round(materialCost * 100) / 100,
        sizeFactor,
        qualityFactor,
        total: Math.round(total * 100) / 100,
    };
}

describe('Pricing Calculation', () => {
    it('calculates base price correctly', () => {
        const result = calculatePricing({
            modelVolume: 50,
            materialPriceMultiplier: 1.0,
            quality: 'standard',
            quantity: 1,
        });

        expect(result.basePrice).toBe(7.5); // 50 * 0.15
        expect(result.materialCost).toBe(0);
        expect(result.total).toBe(7.5);
    });

    it('applies material multiplier', () => {
        const result = calculatePricing({
            modelVolume: 50,
            materialPriceMultiplier: 1.5, // 50% more expensive
            quality: 'standard',
            quantity: 1,
        });

        expect(result.materialCost).toBe(3.75); // 7.5 * 0.5
        expect(result.total).toBe(11.25); // 7.5 + 3.75
    });

    it('applies quality multiplier', () => {
        const draft = calculatePricing({
            modelVolume: 50,
            materialPriceMultiplier: 1.0,
            quality: 'draft',
            quantity: 1,
        });

        const high = calculatePricing({
            modelVolume: 50,
            materialPriceMultiplier: 1.0,
            quality: 'high',
            quantity: 1,
        });

        expect(draft.total).toBe(6); // 7.5 * 0.8
        expect(high.total).toBe(11.25); // 7.5 * 1.5
    });

    it('applies volume discount for large models', () => {
        const small = calculatePricing({
            modelVolume: 50,
            materialPriceMultiplier: 1.0,
            quality: 'standard',
            quantity: 1,
        });

        const large = calculatePricing({
            modelVolume: 150,
            materialPriceMultiplier: 1.0,
            quality: 'standard',
            quantity: 1,
        });

        expect(small.sizeFactor).toBe(1.0);
        expect(large.sizeFactor).toBe(0.9);
        expect(large.total).toBe(20.25); // 150 * 0.15 * 0.9
    });

    it('multiplies by quantity', () => {
        const result = calculatePricing({
            modelVolume: 50,
            materialPriceMultiplier: 1.0,
            quality: 'standard',
            quantity: 3,
        });

        expect(result.total).toBe(22.5); // 7.5 * 3
    });
});
